SOURCE_DATABASE_HOST = 'rdorchml-scan'
SOURCE_DATABASE_PORT = '1521'
SOURCE_DATABASE_SID = 'R102DNEW'
SOURCE_DATABASE_USER = 'a_raiabd'
SOURCE_DATABASE_PASSWORD = 'raiacons'

TARGET_DATABASE_HOST = 'rdorchml-scan'
TARGET_DATABASE_PORT = '1521'
TARGET_DATABASE_SID = 'R102SNEW'
TARGET_DATABASE_USER = 'a_raiabd'
TARGET_DATABASE_PASSWORD = 'raiacons'

MIGRATION_BATCH_SIZE = 1000
LOGGING_LEVEL = 'INFO'
LOG_DIR = '/var/log/migration/'
